/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import entities.ActualizacionPrecios;
import entities.RegistroVenta;
import entities.Temporada;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author PC WHITE WOLF
 */
public class vstCatalogo extends javax.swing.JFrame {
    ActualizacionPrecios precios = new ActualizacionPrecios();
    SimpleDateFormat _df = new SimpleDateFormat("dd/MM/yyyy");
    DecimalFormat dfm = new DecimalFormat("#.00");  
    RegistroVenta reg = new RegistroVenta();
  
    /**
     * Creates new form vstCatalogo
     */
    public vstCatalogo() {
        
        initComponents();
        
        try{
        Temporada _fecha = new Temporada();
        ActualizacionPrecios _precios = new ActualizacionPrecios();
        vstPrincipal _v2 = new vstPrincipal();
       
        
        
    
            if(_fecha.getfecha1().before(_fecha.getFechaFin()) && _fecha.getfecha1().after(_fecha.getFechaIncio())){
                _precios.setPrecioLimpiezaVidrio(1.10* _precios.getPrecioLimpiezaVidrio());
                _precios.setPrecioEncerado(1.10* _precios.getPrecioEncerado());
                _precios.setPrecioPulido(1.10* _precios.getPrecioPulido());
                _precios.setPrecioLavadoExterior(1.10* _precios.getPrecioLavadoExterior());
                _precios.setPrecioLavadoInterior(1.10* _precios.getPrecioLavadoInterior());
                _precios.setPrecioAspirado(1.10* _precios.getPrecioAspirado());
                _precios.setPrecioServicioCompleto(1.10* _precios.getPrecioServicioCompleto());
                
                labelVidrios.setText(" El precio del lavado de vidrio es de: $"+dfm.format(_precios.getPrecioLimpiezaVidrio()));
                labelEncerado.setText("Encerado: $"+dfm.format(_precios.getPrecioEncerado()));
                labelPulido.setText("Pulido: $"+dfm.format(_precios.getPrecioPulido()));
                labelLavadoExterior.setText("Lavado Exterior: $"+dfm.format(_precios.getPrecioLavadoExterior()));
                labelLavadoInterior.setText("Lavado Interior: $"+dfm.format(_precios.getPrecioLavadoInterior()));
                labelAspirado.setText("Aspirado: $"+dfm.format(_precios.getPrecioAspirado()));
                labelServicioCompleto.setText("Servicio Completo: $"+dfm.format(_precios.getPrecioServicioCompleto())); 
                
            }else{
                labelVidrios.setText(" El precio del lavado de vidrio es de: $"+dfm.format(_precios.getPrecioLimpiezaVidrio()));
                labelEncerado.setText("Encerado: $"+dfm.format(_precios.getPrecioEncerado()));
                labelPulido.setText("Pulido: $"+dfm.format(_precios.getPrecioPulido()));
                labelLavadoExterior.setText("Lavado Exterior: $"+dfm.format(_precios.getPrecioLavadoExterior()));
                labelLavadoInterior.setText("Lavado Interior: $"+dfm.format(_precios.getPrecioLavadoInterior()));
                labelAspirado.setText("Aspirado: $"+dfm.format(_precios.getPrecioAspirado()));
                labelServicioCompleto.setText("Servicio Completo: $"+dfm.format(_precios.getPrecioServicioCompleto())); 
                
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Err", "proteger", JOptionPane.ERROR_MESSAGE);
        }
        
    
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelVidrios = new javax.swing.JLabel();
        bntVidrios = new javax.swing.JButton();
        bntEncerado = new javax.swing.JButton();
        bntPulido = new javax.swing.JButton();
        bntLavadoE = new javax.swing.JButton();
        bntLavadoInterior = new javax.swing.JButton();
        bntAspirado = new javax.swing.JButton();
        bntServicioCompleto = new javax.swing.JButton();
        labelEncerado = new javax.swing.JLabel();
        labelPulido = new javax.swing.JLabel();
        labelLavadoExterior = new javax.swing.JLabel();
        labelLavadoInterior = new javax.swing.JLabel();
        labelAspirado = new javax.swing.JLabel();
        labelServicioCompleto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelTicket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Bienvenido estos son los servicios que ofrece Maniatic Wash");

        labelVidrios.setText("Lavado de vidrios:");

        bntVidrios.setText("agregar");
        bntVidrios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVidriosActionPerformed(evt);
            }
        });

        bntEncerado.setText("agregar");
        bntEncerado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEnceradoActionPerformed(evt);
            }
        });

        bntPulido.setText("agregar");
        bntPulido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPulidoActionPerformed(evt);
            }
        });

        bntLavadoE.setText("agregar");
        bntLavadoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLavadoEActionPerformed(evt);
            }
        });

        bntLavadoInterior.setText("agregar");
        bntLavadoInterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLavadoInteriorActionPerformed(evt);
            }
        });

        bntAspirado.setText("agregar");
        bntAspirado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAspiradoActionPerformed(evt);
            }
        });

        bntServicioCompleto.setText("agregar");
        bntServicioCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntServicioCompletoActionPerformed(evt);
            }
        });

        labelEncerado.setText("Encerado:");

        labelPulido.setText("Pulido");

        labelLavadoExterior.setText("Lavado Exterior");

        labelLavadoInterior.setText("Lavado interior");

        labelAspirado.setText("Aspirado");

        labelServicioCompleto.setText("Servicio completo:");

        jLabel2.setText("Gracias por usar nuestro servicio y apoyarnos, ahora puede generar su ticker");

        labelTicket.setText("Generar ticket");
        labelTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelVidrios)
                    .addComponent(labelEncerado)
                    .addComponent(labelPulido)
                    .addComponent(labelLavadoExterior)
                    .addComponent(labelLavadoInterior)
                    .addComponent(labelAspirado)
                    .addComponent(labelServicioCompleto))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntServicioCompleto)
                    .addComponent(bntAspirado)
                    .addComponent(bntLavadoInterior)
                    .addComponent(bntLavadoE)
                    .addComponent(bntPulido)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntVidrios)
                            .addComponent(bntEncerado))
                        .addGap(207, 207, 207)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTicket)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTicket))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelVidrios)
                                    .addComponent(bntVidrios))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bntEncerado)
                                    .addComponent(labelEncerado))
                                .addGap(45, 45, 45)
                                .addComponent(bntPulido))
                            .addComponent(labelPulido, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntLavadoE)
                    .addComponent(labelLavadoExterior))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntLavadoInterior)
                    .addComponent(labelLavadoInterior))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAspirado)
                    .addComponent(labelAspirado))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntServicioCompleto)
                    .addComponent(labelServicioCompleto))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVidriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVidriosActionPerformed
        reg.setSubtotal(precios.getPrecioLimpiezaVidrio());
        reg.setIva(precios.getPrecioLimpiezaVidrio()*1.16);
        reg.setTotal(reg.getTotal()+reg.getSubtotal()+reg.getIva());
        System.out.println("Limpieza Vidrio: ");
        
        
        
    }//GEN-LAST:event_bntVidriosActionPerformed

    private void bntEnceradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEnceradoActionPerformed
        reg.setSubtotal(precios.getPrecioEncerado());
        reg.setIva(precios.getPrecioEncerado()*1.16);
        reg.setTotal(reg.getTotal()+reg.getSubtotal()+reg.getIva());
        System.out.println("Encerado : ");
    }//GEN-LAST:event_bntEnceradoActionPerformed

    private void bntPulidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPulidoActionPerformed
        reg.setSubtotal(precios.getPrecioPulido());
        reg.setIva(precios.getPrecioPulido()*1.16);
        reg.setTotal(reg.getTotal()+reg.getSubtotal()+reg.getIva());
        System.out.println("Pulido : ");
    }//GEN-LAST:event_bntPulidoActionPerformed

    private void bntLavadoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLavadoEActionPerformed
        reg.setSubtotal(precios.getPrecioLavadoExterior());
        reg.setIva(precios.getPrecioLavadoExterior()*1.16);
        reg.setTotal(reg.getTotal()+reg.getSubtotal()+reg.getIva());
        System.out.println("Lavado Exterior : ");
    }//GEN-LAST:event_bntLavadoEActionPerformed

    private void bntLavadoInteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLavadoInteriorActionPerformed
        reg.setSubtotal(precios.getPrecioLavadoInterior());
        reg.setIva(precios.getPrecioLavadoInterior()*1.16);
        reg.setTotal(reg.getTotal()+reg.getSubtotal()+reg.getIva());
        System.out.println("Lavado Interior: ");
    }//GEN-LAST:event_bntLavadoInteriorActionPerformed

    private void bntAspiradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAspiradoActionPerformed
        reg.setSubtotal(precios.getPrecioAspirado());
        reg.setIva(precios.getPrecioAspirado()*1.16);
        reg.setTotal(reg.getTotal()+reg.getSubtotal()+reg.getIva());
        System.out.println(" Aspirado: ");
    }//GEN-LAST:event_bntAspiradoActionPerformed

    private void bntServicioCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntServicioCompletoActionPerformed
       reg.setSubtotal(precios.getPrecioServicioCompleto());
       reg.setIva(precios.getPrecioServicioCompleto()*1.16);
       reg.setTotal(reg.getTotal()+reg.getSubtotal()+reg.getIva());
       
       System.out.println("Servicio completo: ");
    }//GEN-LAST:event_bntServicioCompletoActionPerformed

    private void labelTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelTicketActionPerformed
    vstTicket _frmTicket = new vstTicket();
   
    _frmTicket.setVisible(true);
    
    
    this.dispose();
    }//GEN-LAST:event_labelTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vstCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vstCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vstCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vstCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vstCatalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAspirado;
    private javax.swing.JButton bntEncerado;
    private javax.swing.JButton bntLavadoE;
    private javax.swing.JButton bntLavadoInterior;
    private javax.swing.JButton bntPulido;
    private javax.swing.JButton bntServicioCompleto;
    private javax.swing.JButton bntVidrios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAspirado;
    private javax.swing.JLabel labelEncerado;
    private javax.swing.JLabel labelLavadoExterior;
    private javax.swing.JLabel labelLavadoInterior;
    private javax.swing.JLabel labelPulido;
    private javax.swing.JLabel labelServicioCompleto;
    private javax.swing.JButton labelTicket;
    private javax.swing.JLabel labelVidrios;
    // End of variables declaration//GEN-END:variables
}
