/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;


import entities.ActualizacionPrecios;
import entities.AltaServicio;
import entities.RegistroVenta;
import java.text.DecimalFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author compu
 */
public class vstTicket extends javax.swing.JFrame {
     
    private DefaultTableModel modelo;
    DecimalFormat dfm = new DecimalFormat("#.00");
    RegistroVenta reg = new RegistroVenta();
    AltaServicio alt = new AltaServicio();
    ActualizacionPrecios precios = new ActualizacionPrecios();

    public vstTicket() {
        initComponents();
        labelVidrio.setText("Lavado vidrio: "+alt.getLimpiezaVidrio()+" y el precio es: "+dfm.format(precios.getPrecioLimpiezaVidrio()));
        labelPulido.setText("Lavado vidrio: "+alt.getPulido()+"y el precio es: "+dfm.format(precios.getPrecioPulido()));
        labelEncerado.setText("Lavado vidrio: "+alt.getEncerado()+" y el precio es: "+dfm.format(precios.getPrecioEncerado()));
        labelExterior.setText("Lavado vidrio: "+alt.getLavadoExterior()+" y el precio es: "+dfm.format(precios.getPrecioLavadoExterior()));
        labelInterior.setText("Lavado vidrio: "+alt.getLavadoInterior()+" y el precio es: "+dfm.format(precios.getPrecioLavadoInterior()));
        labelAspirado.setText("Lavado vidrio: "+alt.getAspirado()+" y el precio es"+dfm.format(precios.getPrecioAspirado()));
        labelCompleto.setText("Lavado vidrio: "+alt.getServicioCompleto()+" y el precio es: "+dfm.format(precios.getPrecioServicioCompleto()));
    
        labelSubtotal.setText("subtotal es: $"+reg.getSubtotal());
        labelIva.setText("El IVA es: $"+reg.getIva());
        labelTotal.setText("El total es de: $"+reg.getTotal());
}
  

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelVidrio = new javax.swing.JLabel();
        labelEncerado = new javax.swing.JLabel();
        labelPulido = new javax.swing.JLabel();
        labelExterior = new javax.swing.JLabel();
        labelInterior = new javax.swing.JLabel();
        labelAspirado = new javax.swing.JLabel();
        labelCompleto = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelSubtotal = new javax.swing.JLabel();
        labelIva = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("MANIATIC WASH®");

        jLabel3.setText("RFC: YYY0101011YYY");

        jLabel4.setText("Regimen fiscal: 601");

        jLabel5.setText("Emitido en: Av Carr. a Aeropuerto de Guaymas 870-Km 3, 85500 Guaymas, Son.");

        labelVidrio.setText("lavado vidrio");

        labelEncerado.setText("encerado");

        labelPulido.setText("pulido");

        labelExterior.setText("exterior");

        labelInterior.setText("interior");

        labelAspirado.setText("aspirado");

        labelCompleto.setText("lavado completo");

        labelTotal.setText("Total");

        labelSubtotal.setText("Sub total");

        labelIva.setText("Iva");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAspirado)
                            .addComponent(labelCompleto)
                            .addComponent(labelEncerado)
                            .addComponent(labelExterior)
                            .addComponent(labelVidrio)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSubtotal)
                                .addGap(42, 42, 42)
                                .addComponent(labelIva)
                                .addGap(37, 37, 37)
                                .addComponent(labelTotal))
                            .addComponent(labelInterior)
                            .addComponent(labelPulido)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelSubtotal)
                        .addComponent(labelIva)
                        .addComponent(labelTotal)))
                .addGap(10, 10, 10)
                .addComponent(labelVidrio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEncerado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPulido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelExterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAspirado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCompleto)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vstTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vstTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vstTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vstTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vstTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAspirado;
    private javax.swing.JLabel labelCompleto;
    private javax.swing.JLabel labelEncerado;
    private javax.swing.JLabel labelExterior;
    private javax.swing.JLabel labelInterior;
    private javax.swing.JLabel labelIva;
    private javax.swing.JLabel labelPulido;
    private javax.swing.JLabel labelSubtotal;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelVidrio;
    // End of variables declaration//GEN-END:variables
}
